parameters:
  setup: []
  rust: nightly

jobs:
  - template: rustfmt.yml
    parameters:
      name: rustfmt_nightly
      rust: ${{ parameters.rust }}
  - template: cargo-clippy.yml
    parameters:
      name: clippy
      rust: ${{ parameters.rust }}
      setup: ${{ parameters.setup }}
