parameters:
  envs: {}
  setup: []
  test_ignored: false
  single_threaded: false
  nightly_feature: ''
  features: ''

jobs:
 - template: test.yml
   parameters:
     name: cargo_test_nightly
     cross: true # also test on Windows and macOS
     rust: nightly
     envs: ${{ parameters.envs }}
     setup: ${{ parameters.setup }}
     test_ignored: ${{ parameters.test_ignored }}
     single_threaded: ${{ parameters.single_threaded }}
     features: "${{ parameters.features }},${{ parameters.nightly_feature }}"
